using System.Collections.Immutable;
using System.Text;
using System.Threading;
using JetBrains.Annotations;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace Celeste.Mod.Roslyn.ModLifecycleAttributes;

// see:
// - https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.md
// - https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.cookbook.md
// - https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/source-generator-guidelines.md

[Generator]
public class ModLifecycleAttributeSourceGenerator : IIncrementalGenerator
{
    internal const string GeneratorNamespace = "Celeste.Mod.Roslyn.ModLifecycleAttributes";

    private const string OnLoadAttributeTypeName = "OnLoadAttribute";
    private const string OnLoadAttributeFqn = $"{GeneratorNamespace}.{OnLoadAttributeTypeName}";

    private const string OnInitializeAttributeTypeName = "OnInitializeAttribute";
    private const string OnInitializeAttributeFqn = $"{GeneratorNamespace}.{OnInitializeAttributeTypeName}";

    private const string OnLoadContentAttributeTypeName = "OnLoadContentAttribute";
    private const string OnLoadContentAttributeFqn = $"{GeneratorNamespace}.{OnLoadContentAttributeTypeName}";

    private const string OnUnloadAttributeTypeName = "OnUnloadAttribute";
    private const string OnUnloadAttributeFqn = $"{GeneratorNamespace}.{OnUnloadAttributeTypeName}";

    private const string GeneratedOutputClass = "LifecycleMethods";
    private const string GeneratedOutputLoadMethod = "OnLoad";
    private const string GeneratedOutputInitializeMethod = "OnInitialize";
    private const string GeneratedOutputLoadContentMethod = "OnLoadContent";
    private const string GeneratedOutputUnloadMethod = "OnUnload";

    [LanguageInjection("C#")]
    private const string LifecycleMethodAttributeDefinitions =
        $"""
        // <auto-generated />
        using System;

        namespace {GeneratorNamespace};

        /// <summary>
        ///   Mark a method to be run when your module's <c>Load()</c> is called.
        /// </summary>
        /// <remarks>
        ///   This adds the method to the <see cref="{GeneratorNamespace}.{GeneratedOutputClass}.{GeneratedOutputLoadMethod}"/> invocation list that is generated at compile-time.<br/>
        /// </remarks>
        [AttributeUsage(AttributeTargets.Method)]
        [Microsoft.CodeAnalysis.Embedded]
        internal sealed class {OnLoadAttributeTypeName} : Attribute;
        
        /// <summary>
        ///   Mark a method to be run when your module's <c>Initialize()</c> is called.
        /// </summary>
        /// <remarks>
        ///   This adds the method to the <see cref="{GeneratorNamespace}.{GeneratedOutputClass}.{GeneratedOutputInitializeMethod}"/> invocation list that is generated at compile-time.<br/>
        /// </remarks>
        [AttributeUsage(AttributeTargets.Method)]
        [Microsoft.CodeAnalysis.Embedded]
        internal sealed class {OnInitializeAttributeTypeName} : Attribute;
        
        /// <summary>
        ///   Mark a method to be run when your module's <c>LoadContent(bool)</c> is called.
        /// </summary>
        /// <remarks>
        ///   This adds the method to the <see cref="{GeneratorNamespace}.{GeneratedOutputClass}.{GeneratedOutputLoadContentMethod}"/> invocation list that is generated at compile-time.<br/>
        /// </remarks>
        [AttributeUsage(AttributeTargets.Method)]
        [Microsoft.CodeAnalysis.Embedded]
        internal sealed class {OnLoadContentAttributeTypeName} : Attribute;
        
        /// <summary>
        ///   Mark a method to be run when your module's <c>Unload()</c> is called.
        /// </summary>
        /// <remarks>
        ///   This adds the method to the <see cref="{GeneratorNamespace}.{GeneratedOutputClass}.{GeneratedOutputUnloadMethod}"/> invocation list that is generated at compile-time.<br/>
        /// </remarks>
        [AttributeUsage(AttributeTargets.Method)]
        [Microsoft.CodeAnalysis.Embedded]
        internal sealed class {OnUnloadAttributeTypeName} : Attribute;
        """;

    [LanguageInjection("C#")]
    private const string EmbeddedAttributeDefinition =
        """
        // <auto-generated />
        namespace Microsoft.CodeAnalysis;

        internal sealed partial class EmbeddedAttribute : global::System.Attribute;
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            // ctx.AddEmbeddedAttributeDefinition() is available in compiler version 3.14.0, but we're using 3.12.0...
            ctx.AddSource(
                "EmbeddedAttribute.g.cs",
                SourceText.From(EmbeddedAttributeDefinition, Encoding.UTF8));

            // add the [OnLoad/OnInitialize/OnLoadContent/OnUnload] attribute definitions
            ctx.AddSource(
                "LifecycleMethodAttributes.g.cs",
                SourceText.From(LifecycleMethodAttributeDefinitions, Encoding.UTF8));
        });

        // select the root namespace from the config options...
        var rootNamespaceProvider = context.AnalyzerConfigOptionsProvider.Select(FindRootNamespace);

        // select each annotated lifecycle method...
        // (https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.cookbook.md#use-forattributewithmetadataname)
        var loadMethodsProvider = context.SyntaxProvider.ForAttributeWithMetadataName(
            OnLoadAttributeFqn, FilterEligibleMethods, LifecycleMethod.AsLoad);

        var initializeMethodsProvider = context.SyntaxProvider.ForAttributeWithMetadataName(
            OnInitializeAttributeFqn, FilterEligibleMethods, LifecycleMethod.AsInitialize);

        var loadContentMethodsProvider = context.SyntaxProvider.ForAttributeWithMetadataName(
            OnLoadContentAttributeFqn, FilterEligibleMethods, LifecycleMethod.AsLoadContent);

        var unloadMethodsProvider = context.SyntaxProvider.ForAttributeWithMetadataName(
            OnUnloadAttributeFqn, FilterEligibleMethods, LifecycleMethod.AsUnload);

        // ...and generate a partial class with a method that calls each respectively annotated method.
        // if there aren't any annotated methods, then the respective LifecycleMethods method won't exist
        // because we return early.
        context.RegisterSourceOutput(
            rootNamespaceProvider.Combine(loadMethodsProvider.Collect()), GenerateLoadMethodSource);

        context.RegisterSourceOutput(
            rootNamespaceProvider.Combine(initializeMethodsProvider.Collect()), GenerateInitializeMethodSource);

        context.RegisterSourceOutput(
            rootNamespaceProvider.Combine(loadContentMethodsProvider.Collect()), GenerateLoadContentMethodSource);

        context.RegisterSourceOutput(
            rootNamespaceProvider.Combine(unloadMethodsProvider.Collect()), GenerateUnloadMethodSource);
    }

    // select the root namespace from the config options, or null if not present
    private static string? FindRootNamespace(AnalyzerConfigOptionsProvider options, CancellationToken token)
        => options.GlobalOptions.TryGetValue("build_property.rootnamespace", out string? @namespace)
            ? @namespace
            : null;

    // i would've checked for validity (like accessibility and static-ness) here, but we actually want the
    // invalid invocation to block compilation in this case.
    // it's the user's responsibility to ensure that the method is accessible, static and has the correct signature;
    // silently failing by not generating the invocation would instead lead to some pretty confusing bugs.
    private static bool FilterEligibleMethods(SyntaxNode node, CancellationToken token)
        // since the attribute can only be applied to methods, this will always be true
        => node is MethodDeclarationSyntax;

    private static void GenerateLoadMethodSource(
        SourceProductionContext source,
        (string? Namespace, ImmutableArray<LifecycleMethod> LoadMethods) value)
    {
        ImmutableArray<LifecycleMethod> loadMethods = value.LoadMethods;
        if (loadMethods.IsEmpty)
            return;

        SimpleSourceGenerator sourceGen = new(value.Namespace);

        sourceGen.WriteLine($"internal static partial class {GeneratedOutputClass}");
        using (sourceGen.UseCodeBlock())
        {
            sourceGen.WriteLine($"/// <summary>");
            sourceGen.WriteLine($"///   Run all methods marked with <see cref=\"{OnLoadAttributeFqn}\"/>.");
            sourceGen.WriteLine($"///   This method should be called in your module's <c>Load()</c> method.");
            sourceGen.WriteLine($"/// </summary>");
            sourceGen.WriteLine($"public static void {GeneratedOutputLoadMethod}()");
            using (sourceGen.UseCodeBlock())
            {
                foreach (LifecycleMethod loadMethod in loadMethods)
                    sourceGen.WriteLine($"{loadMethod.TypeFqn}.{loadMethod.Identifier}();");
            }
        }
        source.AddSource("LifecycleMethods.Load.g.cs", sourceGen.Generate());
    }

    private static void GenerateInitializeMethodSource(
        SourceProductionContext source,
        (string? Namespace, ImmutableArray<LifecycleMethod> InitializeMethods) value)
    {
        ImmutableArray<LifecycleMethod> initializeMethods = value.InitializeMethods;
        if (initializeMethods.IsEmpty)
            return;

        SimpleSourceGenerator sourceGen = new(value.Namespace);

        sourceGen.WriteLine($"internal static partial class {GeneratedOutputClass}");
        using (sourceGen.UseCodeBlock())
        {
            sourceGen.WriteLine($"/// <summary>");
            sourceGen.WriteLine($"///   Run all methods marked with <see cref=\"{OnInitializeAttributeFqn}\"/>.");
            sourceGen.WriteLine($"///   This method should be called in your module's <c>Initialize()</c> method.");
            sourceGen.WriteLine($"/// </summary>");
            sourceGen.WriteLine($"public static void {GeneratedOutputInitializeMethod}()");
            using (sourceGen.UseCodeBlock())
            {
                foreach (LifecycleMethod initializeMethod in initializeMethods)
                    sourceGen.WriteLine($"{initializeMethod.TypeFqn}.{initializeMethod.Identifier}();");
            }
        }
        source.AddSource("LifecycleMethods.Initialize.g.cs", sourceGen.Generate());
    }

    private static void GenerateLoadContentMethodSource(
        SourceProductionContext source,
        (string? Namespace, ImmutableArray<LifecycleMethod> LoadContentMethods) value)
    {
        ImmutableArray<LifecycleMethod> loadContentMethods = value.LoadContentMethods;
        if (loadContentMethods.IsEmpty)
            return;

        SimpleSourceGenerator sourceGen = new(value.Namespace);

        sourceGen.WriteLine($"internal static partial class {GeneratedOutputClass}");
        using (sourceGen.UseCodeBlock())
        {
            sourceGen.WriteLine($"/// <summary>");
            sourceGen.WriteLine($"///   Run all methods marked with <see cref=\"{OnLoadContentAttributeFqn}\"/>.");
            sourceGen.WriteLine($"///   This method should be called in your module's <c>LoadContent()</c> method.");
            sourceGen.WriteLine($"/// </summary>");
            sourceGen.WriteLine($"public static void {GeneratedOutputLoadContentMethod}(bool firstLoad)");
            using (sourceGen.UseCodeBlock())
            {
                foreach (LifecycleMethod loadContentMethod in loadContentMethods)
                    sourceGen.WriteLine($"{loadContentMethod.TypeFqn}.{loadContentMethod.Identifier}(firstLoad);");
            }
        }
        source.AddSource("LifecycleMethods.LoadContent.g.cs", sourceGen.Generate());
    }

    private static void GenerateUnloadMethodSource(
        SourceProductionContext source,
        (string? Namespace, ImmutableArray<LifecycleMethod> UnloadMethods) value)
    {
        ImmutableArray<LifecycleMethod> unloadMethods = value.UnloadMethods;
        if (unloadMethods.IsEmpty)
            return;

        SimpleSourceGenerator sourceGen = new(value.Namespace);

        sourceGen.WriteLine($"internal static partial class {GeneratedOutputClass}");
        using (sourceGen.UseCodeBlock())
        {
            sourceGen.WriteLine($"/// <summary>");
            sourceGen.WriteLine($"///   Run all methods marked with <see cref=\"{OnUnloadAttributeFqn}\"/>.");
            sourceGen.WriteLine($"///   This method should be called in your module's <c>Unload()</c> method.");
            sourceGen.WriteLine($"/// </summary>");
            sourceGen.WriteLine($"public static void {GeneratedOutputUnloadMethod}()");
            using (sourceGen.UseCodeBlock())
            {
                foreach (LifecycleMethod unloadMethod in unloadMethods)
                    sourceGen.WriteLine($"{unloadMethod.TypeFqn}.{unloadMethod.Identifier}();");
            }
        }
        source.AddSource("LifecycleMethods.Unload.g.cs", sourceGen.Generate());
    }
}
